<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/bitrix/modules/main/include/prolog_before.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/local/sitebuilder/lib/auth.php';
sitebuilder_require_auth();

global $APPLICATION, $USER;
$basePath = rtrim(str_replace($_SERVER['DOCUMENT_ROOT'], '', __DIR__), '/');
$siteId = (int)($_GET['siteId'] ?? 0);
foreach ([__DIR__.'/lib/db.php',__DIR__.'/lib/json.php',__DIR__.'/lib/response.php',__DIR__.'/lib/helpers.php',__DIR__.'/lib/access.php'] as $file) require_once $file;
if (!$USER->IsAdmin()) {
    if ($siteId <= 0) { http_response_code(422); die('Не передан siteId.'); }
    sb_require_content_manager($siteId);
}
$isAdmin = $USER->IsAdmin();
$returnUrl = $siteId > 0 ? $basePath . '/settings.php?siteId=' . $siteId : $basePath . '/index.php';
?>
<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SiteBuilder / Оповещения</title><?php $APPLICATION->ShowHead(); ?>
<link rel="stylesheet" href="<?=htmlspecialchars($basePath,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>/assets/admin/admin.css">
<style>.alert-layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(320px,.7fr);gap:16px}.alert-table{width:100%;border-collapse:collapse;min-width:900px}.alert-table th,.alert-table td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}.badge{display:inline-flex;padding:3px 8px;border-radius:999px;font-size:12px;font-weight:800}.critical{background:#fee2e2;color:#991b1b}.warning{background:#fef3c7;color:#92400e}.info{background:#dbeafe;color:#1d4ed8}.open{font-weight:800}.details{white-space:pre-wrap;word-break:break-word;max-height:70vh;overflow:auto}@media(max-width:1050px){.alert-layout{grid-template-columns:1fr}}</style>
</head><body class="sb-admin-body"><div class="sb-page">
<div class="sb-topbar"><div><a class="sb-back-link" href="<?=htmlspecialchars($returnUrl,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>">← Назад</a><h1 class="sb-title">Системные оповещения</h1><p class="sb-subtitle"><?= $siteId>0?'Сайт #'.$siteId:'Все сайты и фоновые процессы' ?></p></div><div class="sb-actions"><a class="sb-btn sb-btn-light" href="<?=htmlspecialchars($basePath,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>/external_resources.php<?= $siteId>0?'?siteId='.$siteId:'' ?>">Внешние ресурсы</a><button class="sb-btn sb-btn-light" id="reloadBtn">Обновить</button></div></div>
<div id="message" class="sb-panel" style="display:none"></div>
<section class="sb-panel"><div class="sb-actions"><label class="sb-field"><span>Статус</span><select class="sb-select" id="status"><option value="">Все</option><option value="open" selected>Открытые</option><option value="acknowledged">Подтверждённые</option><option value="resolved">Закрытые</option></select></label><label class="sb-field"><span>Уровень</span><select class="sb-select" id="severity"><option value="">Все</option><option value="critical">Критические</option><option value="warning">Предупреждения</option><option value="info">Информация</option></select></label><button class="sb-btn sb-btn-primary" id="applyBtn">Применить</button></div></section>
<div class="alert-layout"><section class="sb-panel" style="overflow:auto"><table class="alert-table"><thead><tr><th>ID</th><th>Уровень</th><th>Код</th><th>Сайт</th><th>Статус</th><th>Последнее событие</th><th></th></tr></thead><tbody id="rows"><tr><td colspan="7">Загрузка…</td></tr></tbody></table></section><aside class="sb-panel"><h2 class="sb-panel-title" id="detailTitle">Оповещение</h2><div id="detailActions" class="sb-actions"></div><pre id="detail" class="details">Выберите запись</pre></aside></div>
</div><script>(function(){'use strict';var BASE='<?=CUtil::JSEscape($basePath)?>',SITE=<?=$siteId?>,API=BASE+'/api.php';function sid(){return window.BX&&BX.bitrix_sessid?BX.bitrix_sessid():'<?=CUtil::JSEscape(bitrix_sessid())?>'}async function api(a,d){var r=await fetch(API,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(Object.assign({action:a,sessid:sid()},d||{}))}),t=await r.text(),j;try{j=JSON.parse(t)}catch(e){throw{error:'BAD_JSON_RESPONSE'}}if(!j||j.ok!==true)throw j||{error:'UNKNOWN_ERROR'};return j}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}function msg(t,e){var n=document.getElementById('message');n.style.display='block';n.style.color=e?'#991b1b':'#166534';n.textContent=t}async function load(){var r=await api('system.alert.list',{siteId:SITE,status:document.getElementById('status').value,severity:document.getElementById('severity').value,limit:200}),rows=r.items||[];document.getElementById('rows').innerHTML=rows.length?rows.map(function(x){return '<tr><td>#'+Number(x.id)+'</td><td><span class="badge '+esc(x.severity)+'">'+esc(x.severity)+'</span></td><td><strong>'+esc(x.code)+'</strong><br>'+esc(x.title)+'</td><td>'+(x.siteId?'#'+Number(x.siteId):'—')+'</td><td class="'+esc(x.status)+'">'+esc(x.status)+'</td><td>'+esc(x.lastSeenAt)+'<br>Событий: '+Number(x.occurrences)+'</td><td><button class="sb-btn sb-btn-light sb-btn-small open-alert" data-id="'+Number(x.id)+'">Открыть</button></td></tr>'}).join(''):'<tr><td colspan="7">Оповещений нет</td></tr>'}async function openAlert(id){var r=await api('system.alert.get',{alertId:id}),a=r.alert||{};document.getElementById('detailTitle').textContent='Оповещение #'+id;document.getElementById('detail').textContent=JSON.stringify(a,null,2);var buttons='';if(a.status==='open')buttons+='<button class="sb-btn sb-btn-light ack" data-id="'+id+'">Подтвердить</button>';if(a.status!=='resolved')buttons+='<button class="sb-btn sb-btn-primary resolve" data-id="'+id+'">Закрыть</button>';document.getElementById('detailActions').innerHTML=buttons}document.addEventListener('click',function(e){var b=e.target.closest('.open-alert');if(b)openAlert(Number(b.dataset.id)).catch(function(x){msg(x.error||'Ошибка',true)});b=e.target.closest('.ack');if(b)api('system.alert.ack',{alertId:Number(b.dataset.id)}).then(function(){msg('Оповещение подтверждено',false);return load()}).catch(function(x){msg(x.error||'Ошибка',true)});b=e.target.closest('.resolve');if(b)api('system.alert.resolve',{alertId:Number(b.dataset.id)}).then(function(){msg('Оповещение закрыто',false);return load()}).catch(function(x){msg(x.error||'Ошибка',true)})});document.getElementById('reloadBtn').onclick=load;document.getElementById('applyBtn').onclick=load;load().catch(function(x){msg(x.error||'Ошибка загрузки',true)});})();</script></body></html>
