<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/bitrix/modules/main/include/prolog_before.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/local/sitebuilder/lib/auth.php';
sitebuilder_require_auth();

global $APPLICATION, $USER;
$basePath = rtrim(str_replace($_SERVER['DOCUMENT_ROOT'], '', __DIR__), '/');
$siteId = (int)($_GET['siteId'] ?? 0);
foreach ([__DIR__.'/lib/db.php',__DIR__.'/lib/json.php',__DIR__.'/lib/response.php',__DIR__.'/lib/helpers.php',__DIR__.'/lib/access.php'] as $file) require_once $file;
if (!$USER->IsAdmin()) {
    if ($siteId <= 0) { http_response_code(422); die('Не передан siteId.'); }
    sb_require_content_manager($siteId);
}
$isBitrixAdmin = $USER->IsAdmin();
$returnUrl = $siteId > 0 ? $basePath . '/jobs.php?siteId=' . $siteId : $basePath . '/index.php';
?>
<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SiteBuilder / Состояние очереди</title><?php $APPLICATION->ShowHead(); ?>
<link rel="stylesheet" href="<?= htmlspecialchars($basePath,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>/assets/admin/admin.css">
<style>.health-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.health-card{padding:16px;border:1px solid #e5e7eb;border-radius:12px;background:#fff}.health-value{font-size:28px;font-weight:800;margin-top:6px}.health-status{display:inline-flex;padding:5px 10px;border-radius:999px;font-weight:800}.healthy{background:#dcfce7;color:#166534}.warning{background:#fef3c7;color:#92400e}.critical{background:#fee2e2;color:#991b1b}.health-table{width:100%;border-collapse:collapse}.health-table th,.health-table td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left}.checks{display:grid;gap:8px}.check{padding:10px 12px;border-radius:9px;background:#f8fafc}.check.warning{background:#fffbeb}.check.critical{background:#fef2f2}@media(max-width:900px){.health-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.health-grid{grid-template-columns:1fr}}</style>
</head><body class="sb-admin-body"><div class="sb-page">
<div class="sb-topbar"><div><a class="sb-back-link" href="<?= htmlspecialchars($returnUrl,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>">← Назад</a><h1 class="sb-title">Состояние очереди</h1><p class="sb-subtitle"><?= $siteId>0?'Метрики сайта #'.$siteId:'Общие метрики transactional outbox' ?></p></div><div class="sb-actions"><a class="sb-btn sb-btn-light" href="<?= htmlspecialchars($basePath,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>/alerts.php<?= $siteId>0?'?siteId='.$siteId:'' ?>">Оповещения</a><a class="sb-btn sb-btn-light" href="<?= htmlspecialchars($basePath,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>/external_resources.php<?= $siteId>0?'?siteId='.$siteId:'' ?>">Внешние ресурсы</a><?php if($isBitrixAdmin):?><button class="sb-btn sb-btn-primary" id="runBtn">Запустить worker</button><?php endif;?><button class="sb-btn sb-btn-light" id="reloadBtn">Обновить</button></div></div>
<div id="message" class="sb-panel" style="display:none"></div>
<section class="sb-panel"><div class="sb-actions" style="justify-content:space-between"><div><strong>Итог:</strong> <span id="status" class="health-status">Загрузка…</span></div><div id="checkedAt" class="sb-subtitle"></div></div></section>
<section class="health-grid"><div class="health-card">Готово к запуску<div class="health-value" id="ready">—</div></div><div class="health-card">В работе<div class="health-value" id="running">—</div></div><div class="health-card">С ошибкой<div class="health-value" id="dead">—</div></div><div class="health-card">Старейшее ожидание<div class="health-value" id="oldest">—</div></div><div class="health-card">Критические оповещения<div class="health-value" id="criticalAlerts">—</div></div><div class="health-card">Аномалии ресурсов<div class="health-value" id="resourceAnomalies">—</div></div></section>
<section class="sb-panel"><h2 class="sb-panel-title">Проверки</h2><div id="checks" class="checks">Загрузка…</div></section>
<section class="sb-panel"><h2 class="sb-panel-title">Worker-процессы</h2><div style="overflow:auto"><table class="health-table"><thead><tr><th>Worker</th><th>Статус</th><th>Heartbeat</th><th>Текущее задание</th><th>Всего успешно</th><th>Ошибки</th></tr></thead><tbody id="workers"><tr><td colspan="6">Загрузка…</td></tr></tbody></table></div></section>
<section class="sb-panel"><h2 class="sb-panel-title">Последние 24 часа</h2><pre id="daily" class="sb-output">—</pre></section>
</div><script>(function(){'use strict';var BASE='<?= CUtil::JSEscape($basePath) ?>',SITE=<?= $siteId ?>,ADMIN=<?= $isBitrixAdmin?'true':'false' ?>,API=BASE+'/api.php';function sid(){return window.BX&&BX.bitrix_sessid?BX.bitrix_sessid():'<?= CUtil::JSEscape(bitrix_sessid()) ?>'}async function api(a,d){var r=await fetch(API,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(Object.assign({action:a,sessid:sid()},d||{}))}),t=await r.text(),j;try{j=JSON.parse(t)}catch(e){throw{error:'BAD_JSON_RESPONSE'}}if(!j||j.ok!==true)throw j||{error:'UNKNOWN_ERROR'};return j}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}function msg(t,e){var n=document.getElementById('message');n.style.display='block';n.style.color=e?'#991b1b':'#166534';n.textContent=t}async function load(){var r=await api('job.health',{siteId:SITE}),h=r.health||{},q=h.queue||{},o=h.operations||{};var st=document.getElementById('status');st.textContent=h.status||'unknown';st.className='health-status '+(h.status||'warning');document.getElementById('checkedAt').textContent=h.checkedAt||'';document.getElementById('ready').textContent=Number(q.ready||0);document.getElementById('running').textContent=Number(q.running||0);document.getElementById('dead').textContent=Number(q.dead||0);document.getElementById('oldest').textContent=Number(q.oldestReadySeconds||0)+' c';document.getElementById('criticalAlerts').textContent=Number(o.openCriticalAlerts||0);document.getElementById('resourceAnomalies').textContent=Number(o.externalAnomalies||0);document.getElementById('checks').innerHTML=(h.checks||[]).map(function(x){return '<div class="check '+esc(x.level||'')+'"><strong>'+esc(x.code||'')+'</strong> '+esc(x.seconds!=null?x.seconds+' c':x.count!=null?'('+x.count+')':'')+'</div>'}).join('')||'Проверок нет';document.getElementById('workers').innerHTML=(h.workers||[]).map(function(w){return '<tr><td>'+esc(w.workerId)+'</td><td>'+esc(w.status)+'</td><td>'+Number(w.heartbeatAgeSeconds||0)+' c назад</td><td>'+(w.currentJobId?'#'+Number(w.currentJobId):'—')+'</td><td>'+Number(w.succeededTotal||0)+'</td><td>'+Number(w.deadTotal||0)+'</td></tr>'}).join('')||'<tr><td colspan="6">Worker ещё не запускался</td></tr>';document.getElementById('daily').textContent=JSON.stringify(h.last24Hours||{},null,2)}document.getElementById('reloadBtn').onclick=function(){load().catch(function(e){msg(e.error||'Ошибка',true)})};if(ADMIN)document.getElementById('runBtn').onclick=function(){var b=this;b.disabled=true;api('job.run',{limit:20}).then(function(r){msg('Worker завершён: '+JSON.stringify(r.result||{}),false);return load()}).catch(function(e){msg(e.error||'Ошибка',true)}).finally(function(){b.disabled=false})};load().catch(function(e){msg(e.error||'Ошибка загрузки',true)});})();</script></body></html>
